<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_5c84e1fbd8b03',
	'title' => 'Template video',
	'fields' => array(
		array(
			'key' => 'field_5aa23b28ca262',
			'label' => 'Video nổi bật',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5aa239a88b980',
			'label' => 'Link video nổi bật',
			'name' => 'link-video-nb',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Copy link video vào đây, mỗi dòng là 1 video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa239e98b981',
			'label' => 'Title video nổi bật',
			'name' => 'title-nb',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Mỗi dòng là 1 title để gắn với video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa23a098b982',
			'label' => 'Link ảnh nổi bật',
			'name' => 'link-anh-nb',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Mỗi dòng là 1 hình ảnh để gắn với video + title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa23b4eca263',
			'label' => 'List video 1',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5aa33c3946f5e',
			'label' => 'Tiêu đề chuyên mục 1',
			'name' => 'tieu-de-1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5aa23b9fc2144',
			'label' => 'Title video 1',
			'name' => 'title-video-1',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Mỗi dòng là 1 title để gắn với video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa23b86c2143',
			'label' => 'List link video 1',
			'name' => 'list-link-1',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Copy link video vào đây, mỗi dòng là 1 video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa23bb8c2145',
			'label' => 'List link ảnh 1',
			'name' => 'list-anh-1',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Mỗi dòng là 1 hình ảnh để gắn với video + title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa33d1446f5f',
			'label' => 'List video 2',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5aa340ca02dcb',
			'label' => 'Tiêu đề chuyên mục 2',
			'name' => 'tieu-de-2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5aa34af7bc5f7',
			'label' => 'Title video 2',
			'name' => 'title-video-2',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Mỗi dòng là 1 title để gắn với video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa34b99e48b7',
			'label' => 'List link video 2',
			'name' => 'list-link-2',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Copy link video vào đây, mỗi dòng là 1 video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa342b26d885',
			'label' => 'List link ảnh 2',
			'name' => 'list-anh-2',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Mỗi dòng là 1 hình ảnh để gắn với video + title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa33d1746f60',
			'label' => 'List video 3',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5aa340d202dcc',
			'label' => 'Tiêu đề chuyên mục 3',
			'name' => 'tieu-de-3',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5aa34b0426d11',
			'label' => 'Title video 3',
			'name' => 'title-video-3',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Mỗi dòng là 1 title để gắn với video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa34ba41028f',
			'label' => 'List link video 3',
			'name' => 'list-link-3',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Copy link video vào đây, mỗi dòng là 1 video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa342e6983d4',
			'label' => 'List link ảnh 3',
			'name' => 'list-anh-3',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Mỗi dòng là 1 hình ảnh để gắn với video + title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa33d1b46f61',
			'label' => 'List video 4',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_5aa340db02dcd',
			'label' => 'Tiêu đề chuyên mục 4',
			'name' => 'tieu-de-4',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5aa34b0f4e8e6',
			'label' => 'Title video 4',
			'name' => 'title-video-4',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Mỗi dòng là 1 title để gắn với video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa34baee685e',
			'label' => 'List link video 4',
			'name' => 'list-link-4',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Copy link video vào đây, mỗi dòng là 1 video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5aa360179cdc0',
			'label' => 'List ảnh 4',
			'name' => 'list-img-4',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'video-template.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );
} );